version: '3.5'

services:
    filebeat:
        image: docker.elastic.co/beats/filebeat:6.8.15
        volumes:
            - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
            - ./phpfpm.txt:/tmp/phpfpm.txt
    logstash:
        image: docker.elastic.co/logstash/logstash:6.8.15
        entrypoint: ["/tmp/logstash-entrypoint.sh"]
        volumes:
            - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
            - ./logstash-entrypoint.sh:/tmp/logstash-entrypoint.sh:ro
            - ./logstash-input.txt:/tmp/logstash-input.txt
            - ./logstash-output.txt:/tmp/logstash-output.txt
        environment:
            # чтобы logstash лишний раз не делал http://elasticsearch:9200/
            - XPACK_MONITORING_ENABLED=false
        ports:
            - 5046:5046
            # gelf:
            - 12201:12201
            # beats:
            - 31311:31311
            # внутри используется порт 9600 - возможно это дефолтный порт:
            - 9600:9600
            # внутри используется порт 5044 - возможно это дефолтный порт:
            - 5044:5044
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.8.15
        volumes:
            - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
        environment:
            - http.host=0.0.0.0
            - transport.host=127.0.0.1
        ports:
            - 9200:9200
